name: Test-1

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["**"]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
      - name: Get current date
        id: date
        shell: pwsh
        run: |
          $date = Get-Date -Format "yyyy-MM-ddTHH_mm_ss"
          echo "date=$date" >> $env:GITHUB_ENV
